### PR TITLE
Refactor and bug fixes

### PR DESCRIPTION
**Pull request by tuvo1106**
Minor Bug Fixes:
- Fixed italics on the checks, so the emojis look a lot cleaner
- Removed a lot of redundant hide() functions
- Combined consecutive JQuery functions on the same selector to improve performance

Refactors:
- Abstracted a lot of the logic in main jquery function into helper functions. Makes for much cleaner code and easier debugging
- Abstracted all API calls into own file
- Changed most HTML ID's into classes, makes for better reusability
- Changed a lot of HTML class names into more descriptive names to avoid confusion (i.e. #failing, #showing)
- Changed js file into a module, this allows imports/exports

### CODE REVIEW

**Comment by arthurdamm** [comment]
I'm confused by the comment that the setTImeout needed to be fixed. It appeared to always work correctly in testing and the console.log() always showed at the right intervals. In the master branch this is the code that last existed:
 setTimeout(pollResult, 2000)
But in the pull request it is changing from:
setTimeout(pollResult(dataId, authToken), 4000)

The former, current master branch, is passing a function reference. The new change is calling a function inside the timeout inappropriately.

This does not appear to be broken in the master branch but a fix to a local filesystem issue?

Also this will not improve user performance because it was never the 1000 polls per hour that exceeded the limit (for the deployed branches) but the 30 corrections per hour...

**Comment by arthurdamm** [comment]
I am pretty sure that Major Bug fix was on your own branch/fork Tu? The deployed CheckerBuddy never had that bug.

**Comment by arthurdamm** [comment]
Hopefully there are not other sync issues?

**Comment by arthurdamm** [comment]
Aside from the aforementioned major issue, the only other comment I would make is that I would single quotes were considered better standard in JS than double quotes? But the refactors changes that. Not big problem of course, just commenting.

Other than that a lot of the refactors looks really good and some of it like refactoring the functions with arguments I wanted to do as well so good job and thank you!

**Comment by tuvo1106** [comment]
I stand corrected. In original code, pollResult was passed in as a reference and I changed it to be explicitly called. I will retract the major bug fix statement. I will fix the single quote issue with my linter and resubmit.

**Pull request closed without merging**
